services:
  ecommerceapi:
    image: ecommerceapi
    build:
      context: .
      dockerfile: ECommerceAPI/Dockerfile

  ecommerceapi-1:
    image: ecommerceapi-1
    build:
      context: .
      dockerfile: ECommerceAPI/Dockerfile
